### PR TITLE
PODS-8959 - Play3 migration

### PR DESCRIPTION
**Pull request by LauraToddCodes**

### CODE REVIEW

**Comment by LauraToddCodes** [comment]
rebuild

**Comment by PavelVjalicin** [comment]
> * `uk.gov.hmrc.sbt-auto-build` can be updated to `3.19.0` in [project/plugins.sbt](https://github.com/hmrc/pension-scheme-event-reporting-frontend/blob/play3-migration/project/plugins.sbt#L7)
> * Runtime issues may occur. Change `org.playframework.sbt-plugin` to `3.0.1` in [project/plugins.sbt](https://github.com/hmrc/pension-scheme-event-reporting-frontend/blob/play3-migration/project/plugins.sbt#L11) - to match what `uk.gov.hmrc.bootstrap-frontend-play-30` uses

Can we make above changes please.

**Comment by LauraToddCodes** [comment]
rebuild

**Review by PavelVjalicin — APPROVED** [review]
LGTM

**Pull request merged**
